### ISSUE TITLE
Wrong format when using HDMI camera

### ISSUE THREAD

**Issue by casbolwerk** [dusty-nv/jetson-utils#108]
Hi @dusty-nv ! Thanks for all the work on this repo and jetson-inference.

I've been trying to get the jetson-inference C++ builds to work with a v4l2 device. It fails at the point where this repo's gstCamera.cpp decides on the format for the device. It says it finds 3 available formats, where 2 are the same NV12 format and one is I420. I need it to select NV12, because I420 doesn't work (don't exactly know why, I'm not a gstreamer expert by any means). It seems to prefer I420 though, because of the `gstCamera::matchCaps` function that selects I420. What would you suggest to do here? Do I need to make a custom format selection?

```
[gstreamer] gstCamera -- found 3 caps for v4l2 device /dev/video0
[gstreamer] [0] video/x-raw, format=(string)I420, width=(int)3840, height=(int)2160, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)30/1;
[gstreamer] [1] video/x-raw, format=(string)NV12, width=(int)3840, height=(int)2160, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)30/1;
[gstreamer] [2] video/x-raw, format=(string)NV12, width=(int)3840, height=(int)2160, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)30/1;
[gstreamer] gstCamera -- selected device profile:  codec=raw format=i420 width=3840 height=2160
[gstreamer] gstCamera pipeline string:
[gstreamer] v4l2src device=/dev/video0 ! video/x-raw, format=(string)I420, width=(int)3840, height=(int)2160 ! appsink name=mysink
```

The error that it gives when running any jetson-inference build, which works when running through an RTSP stream.

```
[gstreamer] gstreamer v4l2src0 ERROR Device '/dev/video0' cannot capture in the specified format
[gstreamer] gstreamer Debugging info: gstv4l2object.c(3788): gst_v4l2_object_set_format_full (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
Tried to capture in YU12, but device returned format NV12
[gstreamer] gstreamer v4l2src0 ERROR Internal data stream error.
[gstreamer] gstreamer Debugging info: gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
[gstreamer] gstreamer changed state from READY to PAUSED ==> mysink
detectnet:  failed to capture video frame
detectnet:  failed to capture video frame
```

Here is the output from the `v4l2-ctl -d /dev/video0 --list-formats-ext` command btw.

```
ioctl: VIDIOC_ENUM_FMT
        Index       : 0
        Type        : Video Capture
        Pixel Format: 'NV12'
        Name        : Y/CbCr 4:2:0
                Size: Discrete 3840x2160
                        Interval: Discrete 0.033s (30.000 fps)

        Index       : 1
        Type        : Video Capture
        Pixel Format: 'NV12'
        Name        : Y/CbCr 4:2:0
                Size: Discrete 3840x2160
                        Interval: Discrete 0.033s (30.000 fps)

        Index       : 2
        Type        : Video Capture
        Pixel Format: 'YU12'
        Name        : Planar YUV 4:2:0
                Size: Discrete 3840x2160
                        Interval: Discrete 0.033s (30.000 fps)
```

And finally a working command outside of this repo's cameraCapture `gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw, format=(string)NV12, width=(int)3840, height=(int)2160' ! omxh264enc ! 'video/x-h264, stream-format=(string)byte-stream' ! h264parse ! qtmux ! filesink location=test.mp4 -e`

Thanks again!

**Comment by dusty-nv** [comment]
Hi @casbolwerk, interesting - yes, I would recommend modifying `gstCamera::matchCaps()` so that it prioritizes `NV12` format in your case.

It's also interesting that format 0 and 1 are the same in your case.  I wonder if this issue is specific to the camera your are using or its driver.  Is this using an HDMI capture card?
