### ISSUE TITLE
H264 decoder for RTSP stream inside the docker 

### ISSUE THREAD

**Issue by tulseebisen** [dusty-nv/jetson-utils#121]
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/79663448/166668026-8a5eecfe-ecae-4108-b444-7b1554310296.png)
Hello Everyone! Hope You are doing good…
It’s urgent…I am working on Nvidia Jetson AGX Xavier within Dockerized container…I want to take input from RTSP stream…it’s encoding type is H264 and .avi video input.Input stream frame size is 1920x1080 (in code I am resizing that into 1280x720)

I have used this GStreamer pipeline

cap = cv2.VideoCapture(‘rtspsrc location=“rtsp_link” latency=200 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! appsink’, cv2.CAP_GSTREAMER)

It is able to read the frames but after reading frames, frames got completely blurred ,that’s why object detection is not happening.
Kindly help me to solve this issue ASAP. Thank You!

**Comment by dusty-nv** [comment]
> cap = cv2.VideoCapture(‘rtspsrc location=“rtsp_link” latency=200 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! appsink’, cv2.CAP_GSTREAMER)

Hi @tulseebisen, since your issue is unrelated to jetson-utils library, I suggest that you post this to the Jetson AGX Xavier forum:  https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-agx-xavier/75

**Comment by tulseebisen** [comment]
@dusty-nv Oh..Thank You!
