### ISSUE TITLE
script or steps to add wifi to sdcard image

### ISSUE THREAD

**Issue by AndreV84** [dusty-nv/jetson-utils#142]
@dusty-nv 
May I pick your brain for a moment, please?  Do you know what exactly edits need to be made to nx sdcard image filesystem to add a simple wifi connection that will automatically connect on a first boot?
so far I tried adding wpa_supplicant as in the tutorial below but it doesn't seem loaded by default setup of nx sdcard image https://docs.duckietown.org/daffy/opmanual_duckiebot/out/duckiebot_network.html

**Comment by dusty-nv** [comment]
Hey @AndreV84, I don't know how to do it with a file, but personally I connect to wifi with nmcli tool:

``` bash
sudo apt-get install network-manager
sudo nmcli device wifi connect <SSID> password <your password>
```

It's persistent on boot.

**Comment by AndreV84** [comment]
@dusty-nv ,
Thank you for the update!
However, the situation requires that first boot from sdcard needs the connection already
 as the devkit is deep into robot without option to connect by any cable; 
only to add sdcard can be easily added to the devkit  then remote connection over ssh need to exist already
 thank you for your suggestion though

**Comment by AndreV84** [comment]
they somehow implemented it at their sdcard
https://github.com/duckietown/duckietown-shell-commands/blob/daffy/init_sd_card/constants.py#L34-L66
but how to apply it to default nvidia supplied sdcard image is a challenge with no solution as it seems

**Comment by dusty-nv** [comment]
@tokk-nv knows about SD card images

**Comment by AndreV84** [comment]
thank you for the pointer!  posted to their repo for a feedback https://github.com/NVIDIA-AI-IOT/jetcard/issues/45
