### ISSUE TITLE
[Feature Request] Add AddOutput function to Python VideoOutput 

### ISSUE THREAD

**Issue by genevanmeter** [dusty-nv/jetson-utils#173]
With C++, you can add several outputs to a VideoOutput with the AddOutput so one encoding can go multiple destinations.  That function is not available on the Python side.

**Comment by dusty-nv** [comment]
That is really just to transparently hide having a display that's auto-created in addition to the primary output.  It does not share encoded/compressed video, and you can just create multiple videoOutput interfaces.

________________________________
From: Gene VanMeter ***@***.***>
Sent: Wednesday, October 25, 2023 2:22:42 PM
To: dusty-nv/jetson-utils ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-utils] [Feature Request] Add AddOutput function to Python VideoOutput (Issue #173)


With C++, you can add several outputs to a VideoOutput with the AddOutput so one encoding can go multiple destinations. That function is not available on the Python side.

**Comment by genevanmeter** [comment]
That makes sense.  Thank you.
