### ISSUE TITLE
gstUtility and IMAGE_GRAY8

### ISSUE THREAD

**Issue by pedson** [dusty-nv/jetson-utils#194]
Hi.  Thanks for these helpful libraries.

Is there a reason `gst_parse_format` and `gst_format_to_string` do not include `IMAGE_GRAY8`?  I have a grayscale camera that was failing in video-viewer and any of the examples due to `IMAGE_UNKNOWN`.  Adding `IMAGE_GRAY8` as a supported value in those functions resolved this.

Is this worth a small pull request, or is there a reason for it not to be supported there that I did not notice?

**Comment by dusty-nv** [comment]
Hi @pedson, I think the only reason is that I never had a monochrome camera with grayscale formats to use, but if it works for you would be happy to accept a PR!  Thanks 👍
