### ISSUE TITLE
[gstreamer] gstDecoder::Capture() -- an error occurred retrieving the next image buffer

### ISSUE THREAD

**Issue by JIA-HONG-CHU** [dusty-nv/jetson-utils#225]
When I use videosource to loop a video (loops=-1), it runs into issues after a few hours. Is there a solution for this? Thank you.

[gstreamer] gstDecoder::Capture() -- an error occurred retrieving the next image buffer
19:48:30 | ERROR | Exception occurred during video source capture of "/data/videos/demo/Forbidden_zone_advan.mp4"

Traceback (most recent call last):
File "/opt/NanoLLM/nano_llm/plugins/video/video_source.py", line 159, in run
img = self.capture()
File "/opt/NanoLLM/nano_llm/plugins/video/video_source.py", line 97, in capture
image = self.stream.Capture(format='rgb8', timeout=timeout, stream=cuda_stream)
Exception: jetson.utils -- videoSource failed to capture image

**Comment by dusty-nv** [comment]
Hi @JIA-HONG-CHU, for those kind of issues, would recommend to wrap the capture code in try/except exception handler, and to recreate the video source connection on failures.  Here is one such example of adding the additional logic for reconnection:

https://github.com/dusty-nv/NanoLLM/blob/3946278f36d4871353ce4f69229d887b28f380e0/nano_llm/plugins/video/video_source.py#L81

**Comment by JIA-HONG-CHU** [comment]
ok, thanks.
