### ISSUE TITLE
Examples for Video Encoding/Decoding

### ISSUE THREAD

**Issue by rose-jinyang** [dusty-nv/jetson-utils#29]
Hello
How are you?
Thanks for contributing this project.
I think that the content of README is poor.
Could u provide some examples for video encoding/decoding in C++?
Thanks.

**Comment by dusty-nv** [comment]
Hi @rose-jinyang, please see this guide from the main jetson-inference project:   https://github.com/dusty-nv/jetson-inference/blob/dev/docs/aux-streaming.md

**Comment by rose-jinyang** [comment]
thanks
