### ISSUE TITLE
how I declare flip horizontal in compilation, instead as an argument --input-flip=horizontal

### ISSUE THREAD

**Issue by FPSychotic** [dusty-nv/jetson-utils#45]
it is because I dont know how to call that argument from ros or if I need learn python i.e. and I prefer it get compiled  as flip 180 i.e. 

thanks by make this git

**Comment by dusty-nv** [comment]
Hi @FPSychotic , if you are using ROS node, please refer to my suggestion from here:   https://github.com/dusty-nv/ros_deep_learning/issues/52#issuecomment-720666848
