### ISSUE TITLE
Problem?: use gstEncoder with rtmp push

### ISSUE THREAD

**Issue by jcyhcs** [dusty-nv/jetson-utils#53]
hi,professor:

i use gstEncoder API to encode opencv Mat frame , then push stream to rtmp server with URI like this "rtmp://192.168.1.102:1935/live/livestream", my init code like this:

![image](https://user-images.githubusercontent.com/34532224/109450278-7c533900-7a85-11eb-89b9-1da8d8a33a9c.png)
when i run my program, i get an error:
![image](https://user-images.githubusercontent.com/34532224/109450330-98ef7100-7a85-11eb-942c-2a341dd6b497.png)
then ,why the GST PIPELINE of rtmp uri become short? just have ip, "live/livestream" has gone! why? 
what can i do?,PLEASE HELP!

**Comment by dusty-nv** [comment]
Hi @jcyhcs, I think you need to change this line of `jetson-inference/utils/codec/gstEncoder.cpp:401`:

https://github.com/dusty-nv/jetson-utils/blob/1f3709f48258c2d75500c35605e8f6f4a3447afc/codec/gstEncoder.cpp#L401

to the following:

``` cpp
ss << uri.string << " ";
```

@socieboy added the RTMP support and I haven't tried it, so I'm not sure if the error you received is actually related to this or not.

BTW after you make the change above, re-run `make` and `sudo make install`

**Comment by socieboy** [comment]
Seems like the pipeline is being created correctly, but in order to go from rtph264pay to rtmpsink we need another element.

**rtmpsink** only **accepts video/x-flv** as source, and **rtph264pay** has **video/x-h264** as sink, we need to use a flvmux before the rmtp sink.

```
rtph264pay -config-interval=1 ! flvmux ! rtmpsink location="rtmo://{SERVER IP}"
```

**Comment by jcyhcs** [comment]
hi, @socieboy  
when i use your gstreamer pipeline, i also get an error: 
![image](https://user-images.githubusercontent.com/34532224/109579297-95b2be80-7b33-11eb-8648-eee61960ae74.png)
when i remove the element "rtph264pay config-interval=1", then got OK!
so ,please tell me, the element is needed? 
thanks

**Comment by socieboy** [comment]
@jcyhcs when you said then got OK! you mean you got the pipeline working and streaming to RTMP?

**Comment by jcyhcs** [comment]
@socieboy  YES! this pipe line WORK GOOD!
![image](https://user-images.githubusercontent.com/34532224/109589028-aae41900-7b44-11eb-8c2d-92f51da11d89.png)
please check!

**Comment by socieboy** [comment]
you are right, we don't need rtph264, that for the other protocol. i will update the code.

**Comment by dusty-nv** [comment]
Patched this in https://github.com/dusty-nv/jetson-utils/commit/ebf55857d60ba0be5c655cacf8eb8e9348ace714
