### ISSUE TITLE
CUDA ERROR when use gstEncoder!please help!

### ISSUE THREAD

**Issue by jcyhcs** [dusty-nv/jetson-utils#56]
hi,prrofessor:
i use gstEncoder API to encode OpenCV Mat frame ,then push stream with RTMP, i use gst pipeline :
![image](https://user-images.githubusercontent.com/34532224/109579898-b2032b00-7b34-11eb-8d1e-dbaa537e3610.png)
and is OK!
then i use Render API to encode a Mat frame , code this:
![image](https://user-images.githubusercontent.com/34532224/109580011-dfe86f80-7b34-11eb-8d01-91b9143d9255.png)
then run the program, i got a CUDA ERROR!:
![image](https://user-images.githubusercontent.com/34532224/109580301-52f1e600-7b35-11eb-9b59-d459f6eb15fd.png)

what's the problem?? and how can i do ?
help me,please!

**Comment by dusty-nv** [comment]
Hi jcyhcs, it needs to be a CUDA pointer that you supply to the function, but you supply CPU-only pointer from OpenCV.   Allocate CUDA memory with cudaAllocMapped() from my cudaMappedMemory.h and memcpy() into it. Then use that CUDA pointer.
________________________________

**Comment by jcyhcs** [comment]
hi @dusty-nv , i modify my code like this:
![image](https://user-images.githubusercontent.com/34532224/109585102-ce579580-7b3d-11eb-8520-fdeca6cf125c.png)
then CUDA encode ok.
BUT i got other ERROR!:
![image](https://user-images.githubusercontent.com/34532224/109585163-ec24fa80-7b3d-11eb-8933-78e81e924dcb.png)
why the pipeline FULL? how can i fix it? PLEASE!

**Comment by lzcchl** [comment]
hello, have you solved the problem?

**Comment by lzcchl** [comment]
I also want to push rtsp stream, however jetson-utils not yet support, but hw-encode in jetson-utils is great to use;

 so I use jetson-utils + rtsp-server, I want to get the buffer which after encoding to H264(H265), do you know how to get?

I guess the buffer which I need is in "gstEncoder.h" that named 'RingBuffer mBufferYUV', but I haven't test it, if you also have same demand we can finish together.

**Comment by dusty-nv** [comment]
> I guess the buffer which I need is in "gstEncoder.h" that named 'RingBuffer mBufferYUV', but I haven't test it, if you also have same demand we can finish together.

Hi @lzcchl, the encoded output isn't typically directly accessible in the code, instead GStreamer handles it (i.e. in filesink or rtpsink).   The `mBufferYUV` are the inputs that have been transformed to YUV colorspace before being sent to GStreamer for compression/transport.

Is there a GStreamer-based RTSP server element that could be integrated into the pipeline?   For example, https://github.com/GStreamer/gst-rtsp-server

This would be the ideal way, to have it all stay inside GStreamer.

**Comment by dusty-nv** [comment]
> > I guess the buffer which I need is in "gstEncoder.h" that named 'RingBuffer mBufferYUV', but I haven't test it, if you also have same demand we can finish together.
> 
> Hi @lzcchl, the encoded output isn't typically directly accessible in the code, instead GStreamer handles it (i.e. in filesink or rtpsink). The `mBufferYUV` are the inputs that have been transformed to YUV colorspace before being sent to GStreamer for compression/transport.
> 
> Is there a GStreamer-based RTSP server element that could be integrated into the pipeline? For example, https://github.com/GStreamer/gst-rtsp-server
> 
> This would be the ideal way, to have it all stay inside GStreamer.
