### ISSUE TITLE
run video-viewer,gpu usage around 100%, jetson shutdown itself

### ISSUE THREAD

**Issue by themannoshoes** [dusty-nv/jetson-utils#65]
### ENV:
device1: jetson nano 4G
device2:  sony video ,2160*2048, fcb-cv7520a
jetson power mode: MAXN
test software or app:  video-viewer (jetson-utils/build/)
test tools: gpuGraphTX [https://github.com/jetsonhacks/gpuGraphTX](url)

Hello
&emsp;I am using the video-viewer to test camera and video on the jetson nano, and I use gpuGraphTX  to check the gpu status. When I run "./video-viewer /dev/video*" to display the video stream, the gpu usage is up to around 100%, and somtimes jetson nano would shutdown itself. However, when i use the mplayer tools to display the videostream, such as running "mplayer tv:// -tv driver=v4l2:device=/dev/video*", the jetson is working good and never shutdown itself.

&emsp;It seems  the video device is ok, and i don't know if there is problem using the video-viewer with  2160*2048 device.

**Comment by dusty-nv** [comment]
Hi @themannoshoes, if you run the board in 5W model (`sudo nvpmodel -m 1`) does it still shut down?   If not, it would indicate that your power supply is not capable of handling 10W mode (MAX-N)

mplayer may not use the GPU for colorspace conversion / formatting, whereas my code in jetson-inference does.  I have not used it on a 2K video source before.
