### ISSUE TITLE
gstCamera don't have framerate option, how modify the framerate??

### ISSUE THREAD

**Issue by jcyhcs** [dusty-nv/jetson-utils#80]
hi,professor!

i use your gstCamera module to get video from USB camera, the USB camera output two format: YUY2 and mjpeg, both can reach max 60 fps, but my application can't deal with 60fps, so i need modify the framerate ,example: 30fps, but the gstCamera module can't modify framerate!
this function is very important, so ,please finish it!
thanks a lot!

**Comment by dusty-nv** [comment]
Hi @jcyhcs, there are two options that come to mind:

(1) you could add a gstreamer [videorate](https://gstreamer.freedesktop.org/documentation/videorate/index.html?gi-language=c) element after v4l2src element here:

https://github.com/dusty-nv/jetson-utils/blob/ebab1914877a51d4d33fa9b1f01b168adb712a32/camera/gstCamera.cpp#L155

(2) you could simple call `camera.Capture()` from your script less frequently, or wait()

If you make code changes to gstCamera.cpp, re-run `make && sudo make install`
